name: Flutter Build & Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch:  

jobs:
  build_and_deploy:
    name: Build & Deploy to Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.1'

    - name: Install dependencies
      run: flutter pub get
    
    - name: Set API_KEY environment variable
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        echo "API_KEY=$API_KEY" >> $GITHUB_ENV

    - name: Build APK
      run: |
        flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase App Distribution
      env:
        FIREBASE_ACCOUNT_SERVICE: ${{ secrets.FIREBASE_ACCOUNT_SERVICE }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      run: |
        echo "$FIREBASE_ACCOUNT_SERVICE" > firebase-service-account-key.json
        
        npx firebase-tools@11.30.0 appdistribution:distribute \
          --app "$FIREBASE_APP_ID" \
          --groups "testers" \
          --release-notes "New version available for testing" \
          --service-account-file "./firebase-service-account-key.json" \
          "build/app/outputs/flutter-apk/app-release.apk"